### PR TITLE
Bind mouse middle click to close windows (ProjectGreybeard/bugs#21)

### PR DESCRIPTION
**Pull request by m4u9**
Allows to use mouse or touchpad middle click to close windows.

### CODE REVIEW

**Comment by mcepl** [comment]
That is not a good idea to put it to the general configuration. If anybody needs it, they can add it to their `~/`, but some of us actually use middle-button for something useful.

**Comment by m4u9** [comment]
It only activates when you middle-click the window title area. 

What uses do you have as examples?

**Comment by sysrich** [comment]
@mcepl PING - @m4u9 asked a question

**Comment by mcepl** [comment]
Answer is that I was wrong and forgot to say it aloud. Yes, this is perfect.

**Review by mcepl — APPROVED** [review]
This will teach me not to read just two lines of changes, but open whole file!

**Pull request merged**
